### ISSUE TITLE
Fullscreen camera size

### ISSUE THREAD

**Issue by yenyih** [gruhn/vue-qrcode-reader#83]
Hi,
First of all, great work and a very nice piece of code!

I am using this in browsers on mobile devices and tablets. May I know how to make the camera full screen based on different devices screen size (Just like WhatsApp camera scan) ? Is it possible to emit the canvas width and height so that can pass in a custom width and height?

**Comment by gruhn** [comment]
thanks 😁 

I'd suggest you wrap the component in `div` that occupies the entire viewport. Somewhat like this:

```html
<div class="fullscreen">
   <qrcode-steam></qrcode-stream>
</div>
```
```css
.fullscreen {
    position: fixed;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    z-index: 100;
    background-color: black;
    display: flex;
    flex-flow: column nowrap;
    justify-content: center;
}
```

QrcodeStream automatically fills the space available up to the resolution provided by the camera. For most mobile devices this should be sufficient to fill the hole viewport.

Of course this leaves the address bar visible. Unless you are in [PWA mode](https://developers.google.com/web/progressive-web-apps/).

Alternatively, you can use the [Fullscreen API](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen) on the root element:

```html
<qrcode-steam ref="rootElement"></qrcode-stream>
```
```js
this.$refs.rootElement.requestFullscreen()
```

This however will prompt users with a permission dialog. Since you are already asking for camera access permission this might be a little bit too invasive.

Please close this issue if this answers your question.
