### ISSUE TITLE
How to mirror the camera?

### ISSUE THREAD

**Issue by allenwalker2015** [gruhn/vue-qrcode-reader#95]
There's a way to mirror the camera? i'm really interest to mirror the camera cuz that makes a little bit easier to put the phone in the designed area

**Comment by gruhn** [comment]
You mean mirror horizontally? You can use CSS transformations:

```html
<qrcode-stream class="mirror"></qrcode-stream>
```
```css
.mirror {
  transform: scaleX(-1);
}
```
